In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
array1 = np.array([1, 2, 3, 4, 5])
array1



array([1, 2, 3, 4, 5])

In [5]:
array2 = np.arange(0, 20, 2)
array2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
array3 = np.linspace(-5, 5, 101)
array3


array([-5. , -4.9, -4.8, -4.7, -4.6, -4.5, -4.4, -4.3, -4.2, -4.1, -4. ,
       -3.9, -3.8, -3.7, -3.6, -3.5, -3.4, -3.3, -3.2, -3.1, -3. , -2.9,
       -2.8, -2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2. , -1.9, -1.8,
       -1.7, -1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1. , -0.9, -0.8, -0.7,
       -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
        0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,  1.5,
        1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,
        2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,
        3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,
        4.9,  5. ])

In [7]:
array4 = np.random.rand(10)
array4


array([0.47361336, 0.65016559, 0.7942122 , 0.69198854, 0.6536973 ,
       0.42511825, 0.74429416, 0.16122141, 0.4805231 , 0.91915575])

In [8]:
array5 = np.random.randint(1, 100, 10)
array5


array([54, 10, 33, 78,  1, 35, 40, 31, 54, 66])

In [9]:
array6 = np.random.normal(50, 10, 20)
array6


array([61.82287813, 47.79882231, 69.56114015, 41.63809716, 53.95678947,
       22.53399605, 32.59356302, 52.54142028, 32.96012258, 42.12246801,
       63.51398131, 31.57981137, 64.15896192, 43.59694541, 44.03860456,
       58.84428912, 58.75195269, 48.43475259, 60.35360124, 55.90287285])

In [10]:
array7 = np.array([[1, 2, 3], [4, 5, 6]])
array7


array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
array8 = np.zeros((3, 4))
array8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
array9 = np.ones((3, 4))
array9


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
array10 = np.full((3, 4), 10)
array10


array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [15]:
array11 = np.eye(4)
array11


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
array12 = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
array12


array([[1, 2, 3],
       [4, 5, 6]])